# For initial deployment use `docker-compose -f stack.yml up`
# After that, use the Docker Desktop to start the Database, I tried using a volume but it never worked
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_LINK}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOE_PASSWORD}